// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Playlist.Models;
using System;

namespace Playlist.Migrations
{
    [DbContext(typeof(PlaylistContext))]
    [Migration("20180423155001_new_schema")]
    partial class new_schema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Playlist.Models.Musique", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<double>("Duree");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("PlaylistModelId");

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("PlaylistModelId");

                    b.ToTable("Musique");
                });

            modelBuilder.Entity("Playlist.Models.PlaylistModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<bool>("IsPublic");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("ProprietaireName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Playlist.Models.Tags", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PlaylistModelId");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistModelId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Playlist.Models.Musique", b =>
                {
                    b.HasOne("Playlist.Models.PlaylistModel")
                        .WithMany("Musiques")
                        .HasForeignKey("PlaylistModelId");
                });

            modelBuilder.Entity("Playlist.Models.Tags", b =>
                {
                    b.HasOne("Playlist.Models.PlaylistModel")
                        .WithMany("Tags")
                        .HasForeignKey("PlaylistModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
