// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Playlist.Models;
using System;

namespace Playlist.Migrations
{
    [DbContext(typeof(PlaylistContext))]
    [Migration("20180421153752_Playlist_update")]
    partial class Playlist_update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Playlist.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("UserName")
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Playlist.Models.Musique", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PlaylistModelId");

                    b.Property<string>("URL")
                        .IsRequired();

                    b.Property<string>("description")
                        .HasMaxLength(500);

                    b.Property<double>("duree");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.HasIndex("PlaylistModelId");

                    b.ToTable("Musique");
                });

            modelBuilder.Entity("Playlist.Models.PlaylistModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("description")
                        .HasMaxLength(500);

                    b.Property<bool>("isPublic");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("proprietaire_name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Playlist.Models.Tags", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PlaylistModelId");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistModelId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Playlist.Models.Musique", b =>
                {
                    b.HasOne("Playlist.Models.PlaylistModel")
                        .WithMany("contenu")
                        .HasForeignKey("PlaylistModelId");
                });

            modelBuilder.Entity("Playlist.Models.Tags", b =>
                {
                    b.HasOne("Playlist.Models.PlaylistModel")
                        .WithMany("tags")
                        .HasForeignKey("PlaylistModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
