// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebApplication1.Models;

namespace Playlist.Migrations
{
    [DbContext(typeof(PlaylistContext))]
    [Migration("20180419221454_Playlist")]
    partial class Playlist
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("WebApplication1.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApplication1.Models.Musique", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PlaylistId");

                    b.Property<string>("description");

                    b.Property<double>("duree");

                    b.Property<string>("nom");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.ToTable("Musique");
                });

            modelBuilder.Entity("WebApplication1.Models.Playlist", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("description");

                    b.Property<bool>("isPublic");

                    b.Property<string>("nom");

                    b.Property<string>("proprietaireId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("proprietaireId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("WebApplication1.Models.Musique", b =>
                {
                    b.HasOne("WebApplication1.Models.Playlist")
                        .WithMany("contenu")
                        .HasForeignKey("PlaylistId");
                });

            modelBuilder.Entity("WebApplication1.Models.Playlist", b =>
                {
                    b.HasOne("WebApplication1.Models.ApplicationUser", "proprietaire")
                        .WithMany()
                        .HasForeignKey("proprietaireId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
